### ISSUE TITLE
Guid uri template path/query parameter values should be normalized to string

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-abstractions-php#135]
the std uri template library does not handle guids, and wont because it's not a standard API across languages and they don't want to bring on additional dependencies.
We should normalize the value to string (no curlies) before we pass it to the uri template engine.
Originally reported:
https://github.com/std-uritemplate/std-uritemplate/issues/140
https://github.com/microsoft/kiota/issues/4335

Example implementation https://github.com/microsoft/kiota-abstractions-dotnet/blob/5a93d126e9ce30ae332e65f30df7b941e7d7c265/src/RequestInformation.cs#L123

**Comment by andrueastman** [comment]
According to the code at the link below, it looks like the generator does not emit a specific type for uuid/guid types in PHP. These are already normalized to string so it would not be expected to have any type for guid present in the URI.

https://github.com/microsoft/kiota/blob/947d0b3d8835168666edfff1716a2c75c9f9f141/src/Kiota.Builder/Writers/Php/PhpConventionService.cs#L71

If this is intended, I believe this issue can be closed as not GUID would be placed in a request info object.

cc @Ndiritu

**Comment by Ndiritu** [comment]
I agree with closing this @andrueastman. PHP doesn't support GUID types natively & we map these to strings already as linked.

**Comment by andrueastman** [comment]
Thanks for checking @Ndiritu. Closing this one for now.
